apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: rhdh
spec:
  location: ApplicationMenu
  text: Developer Hub
  href: https://rhdh-developer-hub-rhdh.{{ .Values.deployer.domain }}
  applicationMenu:
    section: Red Hat Applications
    imageURL: https://rhdh-developer-hub-rhdh.{{ .Values.deployer.domain }}/favicon.ico
