{{- $clusterDomain := .Values.deployer.domain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  location: ApplicationMenu
  text: HashiCorp Vault
  href: https://vault.{{ $clusterDomain }}/ui/
  applicationMenu:
    section: Red Hat Applications
    imageURL: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbDpzcGFjZT0icHJlc2VydmUiIGlkPSJMYXllcl8xIiB4PSIwIiB5PSIwIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48c3R5bGU+LnN0MXtmaWxsOiMwMDU3NjZ9LnN0MntmaWxsOiMwMGQ4ZmV9LnN0M3tmaWxsOiMwMDhkYTZ9PC9zdHlsZT48cGF0aCBkPSJNMCAxNC41aDUxMmwtMjU2IDQ4M3oiLz48cGF0aCBkPSJNMzE4IDE0Mi45YzAgOC02LjUgMTQuNS0xNC41IDE0LjVzLTE0LjUtNi41LTE0LjUtMTQuNSA2LjUtMTQuNSAxNC41LTE0LjUgMTQuNSA2LjUgMTQuNSAxNC41IiBzdHlsZT0iZmlsbDojMDBhZGNjIi8+PHBhdGggZD0iTTMxOCAxODIuN2MwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41IDE0LjUgNi41IDE0LjUgMTQuNSIgY2xhc3M9InN0MSIvPjxwYXRoIGQ9Ik0zMTggMjIyLjJjMCA4LTYuNSAxNC41LTE0LjUgMTQuNXMtMTQuNS02LjUtMTQuNS0xNC41IDYuNS0xNC41IDE0LjUtMTQuNWM4IC4xIDE0LjUgNi41IDE0LjUgMTQuNSIgY2xhc3M9InN0MiIvPjxwYXRoIGQ9Ik0yMzEuMSAyMjIuMmMwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41YzggLjEgMTQuNSA2LjUgMTQuNSAxNC41IiBjbGFzcz0ic3QzIi8+PHBhdGggZD0iTTIzMS4xIDE4Mi43YzAgOC02LjUgMTQuNS0xNC41IDE0LjVzLTE0LjUtNi41LTE0LjUtMTQuNSA2LjUtMTQuNSAxNC41LTE0LjUgMTQuNSA2LjUgMTQuNSAxNC41bTAtMzkuOGMwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41IDE0LjUgNi41IDE0LjUgMTQuNSIgY2xhc3M9InN0MiIvPjxwYXRoIGQ9Ik0yNzQuNSAxNDIuOWMwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41IDE0LjUgNi41IDE0LjUgMTQuNSIgY2xhc3M9InN0MSIvPjxwYXRoIGQ9Ik0yNzQuNSAxODIuN2MwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41IDE0LjUgNi41IDE0LjUgMTQuNSIgc3R5bGU9ImZpbGw6IzAwYzNlNiIvPjxwYXRoIGQ9Ik0yNzQuNSAyMjIuMmMwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41IDE0LjUgNi41IDE0LjUgMTQuNSIgY2xhc3M9InN0MyIvPjxwYXRoIGQ9Ik0yNzQuNSAyNjIuNGMwIDgtNi41IDE0LjUtMTQuNSAxNC41cy0xNC41LTYuNS0xNC41LTE0LjUgNi41LTE0LjUgMTQuNS0xNC41IDE0LjUgNi41IDE0LjUgMTQuNSIgY2xhc3M9InN0MiIvPjwvc3ZnPg==
