{{- $clusterDomain := .Values.deployer.domain }}
{{- if not $clusterDomain }}
{{- $ingressConfig := lookup "config.openshift.io/v1" "Ingress" "" "cluster" }}
{{- if and $ingressConfig $ingressConfig.spec }}
{{- $clusterDomain = $ingressConfig.spec.domain }}
{{- end }}
{{- end }}
{{- if $clusterDomain }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  host: vault.{{ $clusterDomain }}
  to:
    kind: Service
    name: vault
    weight: 100
  port:
    targetPort: 8200
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
